
[[data]]
"विषयः" = 'संस्कृतम्'
"नाम" = 'संस्कृतयूथम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/samskrita'
"भाषा\n" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'भारतीयविद्वत्-परिषत्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/bvparishat'
"भाषा\n" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'हिन्दु-विद्या'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/hindu-vidya'
"भाषा\n" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'शास्त्रम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/shaastram'
"भाषा\n" = 'संस्कृतम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = ''
"नाम" = 'संस्कृते संवदेम'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/samskrte-samvadema'
"भाषा\n" = 'संस्कृतम्'
"नियमाः" = 'संस्कृतेनैव भाषणम्'
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'संस्कृत-साङ्गणकाः / sanskrit code'
"नाम" = 'sanskrit code'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/sanskrit-programmers'
"भाषा\n" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'पद्यम्'
"नाम" = 'कवयो वयममी'
"सङ्केतः" = 'https://www.facebook.com/groups/padyadhaaraa/?fref=ts'
"भाषा\n" = 'संस्कृतम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Facebook groups'

