
[[data]]
"विषयः" = 'संस्कृतम्'
"नाम" = 'संस्कृतयूथम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/samskrita'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'भारतीयविद्वत्-परिषत्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/bvparishat'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'हिन्दु-विद्या'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/hindu-vidya'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'तन्त्रम् आगमाश्च'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/tantrollAsaH'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'शब्दशास्त्रम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/shabda-shAstram'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'कल्पः, प्रयोगः'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/kalpa-prayoga'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'शास्त्रम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/shaastram'
"भाषा" = 'संस्कृतम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = ''
"नाम" = 'संस्कृते संवदेम'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/samskrte-samvadema'
"भाषा" = 'संस्कृतम्'
"नियमाः" = 'संस्कृतेनैव भाषणम्'
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'संस्कृत-साङ्गणकाः / sanskrit code'
"नाम" = 'sanskrit code'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/sanskrit-programmers'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'पद्यम्'
"नाम" = 'कवयो वयममी'
"सङ्केतः" = 'https://www.facebook.com/groups/padyadhaaraa/?fref=ts'
"भाषा" = 'संस्कृतम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Facebook groups'

[[data]]
"विषयः" = 'इतिहासः'
"नाम" = 'भारतीयदृष्टिः'
"सङ्केतः" = 'http://t.me/SurfingKaliYuga'
"भाषा" = 'English'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Telegram'

[[data]]
"विषयः" = 'हिन्दुत्व-पुंस्त्वम्'
"नाम" = 'रुद्राग्नी'
"सङ्केतः" = 'http://t.me/kaalaagni'
"भाषा" = 'English'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Telegram'

[[data]]
"विषयः" = 'हिन्दुत्वम्'
"नाम" = 'रुद्राग्नी'
"सङ्केतः" = 'http://t.me/CursedRaitaTakes'
"भाषा" = 'English'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Telegram'

