[[data]]
"संज्ञा" = 'प्रगृह्यः'
"गणः" = 'शब्दः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
दूरात् संबोधने जातः प्लुतः।
इत्-उत्-एत्-अन्तं द्विवचनम्।
द्विवचनान्ते  इ उ ए।
अदस् रूपेषु अमू अमी।
निपाताः‌ एकाच् अनाङ्।
ओत्-अन्त-निपातः।
'''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = '''
हरी। अस्मू। अमी। पचेते।
इ इन्द्रः। इ विस्मयार्थे। उ उमेशः।  उ सन्देहे।
अहो!
परन्तु चादिगणे स्थितः आ - आ अहं स्मरामि। आ स्मरणे।
न तु आङ् उपसर्गः (आ +उष्णम् = ओष्णम्।)।
'''

[[data]]
"संज्ञा" = 'प्रत्ययः'
"गणः" = ''
"उपगणः" = 'प्रत्ययः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'यत् शब्दपरिवर्तनम् विदधत्ते उत शब्दग्रहणाय प्रतीयते।'
"सूत्रम्" = 'विधीयते उत प्रतीयते यत्  प्रत्ययः।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अपृक्तः'
"गणः" = ''
"उपगणः" = 'प्रत्ययः'
"गृहितानि/ उदाहरणम्" = 'एक-मात्रवर्णः प्रत्ययः'
"विवरणम्" = ''
"सूत्रम्" = 'अपृक्त एकाल् प्रत्ययः'
"उदाहरणम्" = 'व् ल् य् अ'

[[data]]
"संज्ञा" = 'पदम्'
"गणः" = 'पदम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
सुबन्तानि। तिङन्तानि॥ (लौकिकसंज्ञा।)
सुट् विहाय सुपः प्राक्तन-अनपुंसक-अङ्गः॥'''
"विवरणम्" = ''
"सूत्रम्" = '''
सुप्तिङन्तम् पदम्॥
स्वादिषु असर्वनामस्थाने॥'''
"उदाहरणम्" = 'वाच्+भ्याम् <-- इत्यस्मिन् वाच्।'

[[data]]
"संज्ञा" = 'प्रातिपदिकम्'
"गणः" = 'पदम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = '''
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्॥
कृत्तद्धितसमासाश्च॥
प्रातिपदिकग्रहणे लिङ्गविशिष्टस्यापि ग्रहणम्॥ (परिभाषा)'''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उपपदम्'
"गणः" = 'शब्दः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
",कर्मण्यण्" इत्यनेन कुम्भकारः इति सिध्यति। अत्र कुम्भशब्दस्योपपदसंज्ञा।
एवं धनद इत्यस्मिन् धनशब्दः।'''
"विवरणम्" = 'तृतीयेऽध्याये धात्वधिकारे सूत्रेषु सप्तम्यन्तेन यन् निर्दिष्टं तद् उपपदसंज्ञम्। प्रयोजनं स्वरनिर्देशे।'
"सूत्रम्" = 'तत्रोपपदं सप्तमीस्थम्'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'नियतलिङ्गकम्'
"गणः" = 'पदम्'
"उपगणः" = 'प्रातिपदिकम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'येन प्रातिपदिकेन स्त्रीप्रत्ययादिः न योग्यः।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सत्त्वम्'
"गणः" = 'पदम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'लिङ्ग-सङ्ख्या-अनिव्ताः।'
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = 'च अद्रव्यार्थे'

[[data]]
"संज्ञा" = 'कर्मप्रवचनीयः'
"गणः" = 'पदम्'
"उपगणः" = 'अव्ययम्'
"गृहितानि/ उदाहरणम्" = 'अनु उप प्रति परि अभि अधि सु अति अपि अप आङ् इत्येतेषां कर्मप्रवचनीयसंज्ञा।'
"विवरणम्" = '''
भिन्न-पृष्ठे विवृतम्
'''
"सूत्रम्" = ''
"उदाहरणम्" = 'वृक्षं प्रति विद्युत् विद्योतते।'

[[data]]
"संज्ञा" = 'निपातः, गतिः, उपसर्गः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
भिन्न-पृष्ठे विवृतम्
'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'घुः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'दाधा घ्वदाप् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'घः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'तरप्तमपौ घः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'संख्या'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'बहुगणवतुडति संख्या ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'षट्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'ष्णान्ता षट् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'षट्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'डति च ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'निष्ठा'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'क्तक्तवतू निष्ठा ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'सर्वादीनि सर्वनामानि ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'विभाषा दिक्समासे बहुव्रीहौ ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'न बहुव्रीहौ ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'तृतीयासमासे ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'द्वन्द्वे च ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'विभाषा जसि ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'प्रथमचरमतयाल्पार्धकतिपयनेमाश्च ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'पूर्वपरावरदक्षिणोत्तरापराधराणि'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'स्वमज्ञातिधनाख्यायाम् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनाम'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'अन्तरं बहिर्योगोपसंव्यानयोः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अव्ययम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'स्वरादिनिपातमव्ययम् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अव्ययम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'तद्धितश्चासर्वविभक्तिः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अव्ययम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'कृन्मेजन्तः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अव्ययम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'क्त्वातोसुन्कसुनः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अव्ययम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'अव्ययीभावश्च ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनामस्थानम्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'शि सर्वनामस्थानम् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनामस्थानम्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'सुडनपुंसकस्य ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
