[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लृट्'
"विधिः" = ''
"सूत्रम्" = 'क्षिप्र-वचने लृट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'आशंसा-वचने लिङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'नानद्यतनवत्‌ क्रिया-प्रबन्ध-सामीप्ययोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'भविष्यति मर्यादावचने ऽवरस्मिन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'काल-विभागे चान्-अहोरात्राणाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'परस्मिन् विभाषा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भविष्यति संभावना-परिणाम वचने।'
"परिणामः" = 'लृङ्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'लिङ्निमित्ते लृङ् क्रियातिपत्तौ।'
"प्रभावोदाहरणम्" = 'दक्षिणेन चेदायास्यन् न शकटं पर्यभविस्यत्। यदि कमलकमाह्वास्यन् न शकटं पर्याभविष्यत्। अभोक्ष्यत भवान् घृतेन यदि मत्समीपमागमिष्यत्। भविष्यत् कालविषयम् एतद् वचनम्। भविस्यदपर्याभवनं च हेतुमत्, तत्र हेतुभूतं च कमलकाह्वानम्। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = '''
कुतश्चिद् वैगुण्यादनभिनिर्वृत्तिः क्रियायाः क्रियातिपत्तिः।
'''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भूते संभावना-परिणाम वचने।'
"परिणामः" = 'लृङ्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'भूते च॥'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लृङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लृङ्'
"विधिः" = ''
"सूत्रम्" = 'वोताप्योः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लट्'
"विधिः" = ''
"सूत्रम्" = 'गर्हायां लडपिजात्वोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'विभाषा कथमि लिङ् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'किंवृत्ते लिङ्लृटौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'अनवकॢप्त्यमर्षयोरकिंवृत्ते अपि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'किंकिलास्त्यर्थेषु लृट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'जातुयदोर्लिङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'यच्चयत्रयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'गर्हायां च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'चित्रीकरणे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लृट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लृट्'
"विधिः" = ''
"सूत्रम्" = 'शेषे लृडयदौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'उताप्योः समर्थयोर्लिङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'कामः, इच्छा, अभिलाषः उपपदे'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'कामप्रवेदनेऽकच्चिति ।'
"प्रभावोदाहरणम्" = 'कामो मे भुञ्जीत भवान्। अभिलाषो मे भुञ्जीत भवान्।'
"अभावोदाहरणम्" = ' कच्चिज् जीवति ते माता कच्चिज् जीवति ते पिता। '
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'सम्भवानेऽलमिति चेत्‌ सिद्धाप्रयोगे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'विभाषा धातौ सम्भावनवचनेऽयदि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'हेतुहेतुमतोर्लिङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ् लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ् लोट्'
"विधिः" = ''
"सूत्रम्" = 'इच्छार्थेषु लिङ्लोटौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'तुमुन्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'तुमुन्'
"विधिः" = ''
"सूत्रम्" = 'समानकर्तृकेषु तुमुन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'लिङ् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'इच्छार्थेभ्यो विभाषा वर्तमाने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'विध्यादौ'
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = '''
विधि-निमन्त्रण-आमन्त्रण-अधीष्ट-संप्रश्न-प्रार्थनेषु लिँङ्॥
लोँट् च॥ आशिषि लिँङ्लोँटौ ॥'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = '''
विधिः प्रेरणम्। निमन्त्रणम् नियोगकरणम् (साग्रहम्)। आमन्त्रणम् कामचारकरणम्। अधीष्टः सत्कारपूर्वको व्यापारः। सम्प्रश्नः सम्प्रधारणम्। प्रार्थनम् याच्ञा।

आशंसनम् आशीः, अप्रप्तस्य इष्टस्य अर्थस्य प्राप्तुम् इच्छा।'''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'संभावनायाम्'
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'शकि लिँङ् च (प्रत्ययः परश्च धातोः कृत्याः)'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'विध्यादौ।'
"परिणामः" = 'लोँट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'लोट् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लोट्'
"विधिः" = ''
"सूत्रम्" = 'प्रैषातिसर्गप्राप्तकालेषु कृत्याश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लोट्'
"विधिः" = ''
"सूत्रम्" = 'लिङ् चोर्ध्वमौहूर्तिके ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लोट्'
"विधिः" = ''
"सूत्रम्" = 'स्मे लोट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लोट्'
"विधिः" = ''
"सूत्रम्" = 'अधीष्टे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'तुमुन्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'तुमुन्'
"विधिः" = ''
"सूत्रम्" = 'कालसमयवेलासु तुमुन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लिङ्'
"विधिः" = ''
"सूत्रम्" = 'लिङ् यदि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"विधिः" = ''
"सूत्रम्" = 'अर्हे कृत्यतृचश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"विधिः" = ''
"सूत्रम्" = 'आवश्यकाधमर्ण्ययोर्णिनिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"विधिः" = ''
"सूत्रम्" = 'कृत्याश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'कृत्य-तृच्-णिनि-लिङ्-लोट्'
"विधिः" = ''
"सूत्रम्" = 'शकि लिङ् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'आशिषि।'
"परिणामः" = 'लिङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'आशिषि लिङ्लोटौ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'आशिषि।'
"परिणामः" = 'लोँट्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'आशिषि लिङ्लोटौ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्तिच्-क्त'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'क्तिच्-क्त'
"विधिः" = ''
"सूत्रम्" = 'क्तिच्क्तौ च संज्ञायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'मा-कारे'
"परिणामः" = 'लुँङ्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'माङि लुङ् '
"प्रभावोदाहरणम्" = 'मा भूत्'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'मा-स्म-कारे'
"परिणामः" = 'लँङ्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'स्मोत्तरे लङ् च ।'
"प्रभावोदाहरणम्" = 'मा स्म भवत्।'
"अभावोदाहरणम्" = 'मा तपः आचर। (लोट्)'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्रत्ययार्थाः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययार्थाः'
"विधिः" = ''
"सूत्रम्" = 'धातुसम्बन्धे प्रत्ययाः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्रत्ययार्थाः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययार्थाः'
"विधिः" = ''
"सूत्रम्" = 'क्रियासमभिहारे लोट्; लोटो हिस्वौ; वा च तध्वमोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्रत्ययार्थाः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययार्थाः'
"विधिः" = ''
"सूत्रम्" = 'समुच्चयेऽन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्रत्ययार्थाः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययार्थाः'
"विधिः" = ''
"सूत्रम्" = 'यथाविध्यनुप्रयोगः पूर्वस्मिन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्रत्ययार्थाः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययार्थाः'
"विधिः" = ''
"सूत्रम्" = 'समुच्चये सामान्यवचनस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्रत्ययार्थाः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययार्थाः'
"विधिः" = ''
"सूत्रम्" = 'छन्दसि लुङ्लङ्लिटः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'छन्दसि लिङर्थे।'
"परिणामः" = 'लेँट्'
"प्रासिद्ध्यम्" = '२'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'लिँङ्-अर्थे लेँट्॥'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'छन्दसि कर्तव्ये पणबन्धः।'
"परिणामः" = 'लेँट्'
"प्रासिद्ध्यम्" = '२'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'उपसंवादाशङ्कयोश् च।'
"प्रभावोदाहरणम्" = 'निहारञ्च हरासि मे निहारं निहराणि ते स्वाहा॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
